added db.has for nonsql
PyBase/PyBase pull request #3
Opened 2020-12-04 14:45 UTC by acarkh

2020-12-04 21:57 UTC, Danny2105 requested changes
@NTBBloodbath That reminded me that we will have to change the exceptions a bit so that they are not necessarily displayed via `rich`

2020-12-04 21:57 UTC, Danny2105 commented on pybase_db/pybase_db.py
> +    def has(self, key = str: None):
Syntax error
```suggestion
    def has(self, key: str = None):
```

2020-12-04 21:57 UTC, Danny2105 commented on pybase_db/pybase_db.py
> +            A dictionary which contains all the database objects.
Returns `bool`

2020-12-04 21:57 UTC, Danny2105 commented on pybase_db/pybase_db.py
> +            this.get(key)
It would still show an error if the "key" does not exist via `rich.console` ([#L451](https://github.com/PyBase/PyBase/blob/master/pybase_db/pybase_db.py#L451))

2020-12-04 22:01 UTC, NTBBloodbath commented on pybase_db/pybase_db.py
> +            this.get(key)
Also in Python `self` is used instead of `this`.

2020-12-04 22:06 UTC, Danny2105 commented on pybase_db/pybase_db.py
> +            this.get(key)
Forgot that lol

2020-12-05 12:02 UTC, acarkh commented on pybase_db/pybase_db.py
> +            this.get(key)
I don't understand, I use the exception to understand if the data is available or not.

2020-12-06 02:53 UTC, NTBBloodbath approved these changes
The new method will be pushed to the master branch, but it will be modified in the development branch to adapt it to the new changes.

2020-12-06 02:54 UTC, merged